// File generated by scripts/research-evaluate.ts - DO NOT EDIT DIRECTLY
// Source spec: debounce
// Description: Debounce and throttle higher-order functions with cancellation support.
// Source: unknown | maxLines: 100

import { describe, expect, test } from "bun:test";
import * as debounce_mod from "../debounce";
const debounce = (debounce_mod as any);

describe("debounce", () => {

  test("debounce_fn__delayMs__options_____traili", () => {
    // Requirement: debounce(fn, delayMs, options?) - trailing/leading edge
    expect(debounce).toBeDefined();
  });

  test("throttle_fn__intervalMs____limit_call_ra", () => {
    // Requirement: throttle(fn, intervalMs) - limit call rate
    expect(debounce).toBeDefined();
  });

  test("Both_return_a_wrapped_function_with__can", () => {
    // Requirement: Both return a wrapped function with .cancel() method
    expect(debounce).toBeDefined();
  });

  test("debounce_returns_a_promise_resolving_to_", () => {
    // Requirement: debounce returns a promise resolving to the fn's return value
    expect(debounce).toBeDefined();
  });

  test("TypeScript_generics_preserve_argument_an", () => {
    // Requirement: TypeScript generics preserve argument and return types
    // Type check is done at compile time; this verifies the export exists.
    expect(debounce).toBeDefined();
  });
});
