/**
 * Tests for the make_pdf tool helper (packages/tools/make-pdf.ts).
 *
 * The helper shells out to the canonical renderer CLI. To stay deterministic
 * and offline, most tests point EIGHT_MAKE_PDF_BIN at a tiny stub script that
 * mimics the real CLI contract (prints the absolute output path on its last
 * stdout line, exit 0). A final integration test runs the REAL CLI only when
 * it is actually installed on the host.
 */

import { afterEach, beforeEach, describe, expect, test } from "bun:test";
import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import { CREATIVE_DIR, DEFAULT_MAKE_PDF_BIN, makePdf, resolveMakePdfBin } from "../make-pdf";

let tmpDir: string;
let stubBin: string;

/**
 * Write a stub CLI that echoes a creative-dir path built from --title/--out,
 * matching the real CLI's "last stdout line is the absolute PDF path" contract.
 */
function writeStub(script: string): string {
	const p = path.join(tmpDir, "make-pdf-stub");
	fs.writeFileSync(p, script, { mode: 0o755 });
	fs.chmodSync(p, 0o755);
	return p;
}

beforeEach(() => {
	tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), "make-pdf-test-"));
	// Default stub: print a deterministic creative-dir path on the last line,
	// with a leading log line to prove we capture the LAST line, not the first.
	stubBin = writeStub(
		`#!/usr/bin/env bash\n` +
			`echo "[stub] rendering with fake engine" 1>&2\n` +
			`echo "some preamble on stdout"\n` +
			`echo "${CREATIVE_DIR}/doc-stub.pdf"\n`,
	);
	process.env.EIGHT_MAKE_PDF_BIN = stubBin;
});

afterEach(() => {
	delete process.env.EIGHT_MAKE_PDF_BIN;
	fs.rmSync(tmpDir, { recursive: true, force: true });
});

describe("makePdf", () => {
	test("returns a creative-dir path and document kind", async () => {
		const result = await makePdf({ markdown: "# Hi", title: "Stub" });
		expect(result.kind).toBe("document");
		expect(result.path.startsWith(CREATIVE_DIR)).toBe(true);
		expect(result.path.endsWith(".pdf")).toBe(true);
	});

	test("captures the LAST stdout line as the output path", async () => {
		const result = await makePdf({ markdown: "# Hi" });
		expect(result.path).toBe(`${CREATIVE_DIR}/doc-stub.pdf`);
	});

	test("rejects when no source is provided", async () => {
		await expect(makePdf({ title: "empty" })).rejects.toThrow(/one of/i);
	});

	test("rejects when more than one source is provided", async () => {
		await expect(makePdf({ markdown: "# A", html: "<h1>B</h1>" })).rejects.toThrow(
			/exactly one source/i,
		);
	});

	test("propagates a non-zero exit as a rejection with the stderr reason", async () => {
		process.env.EIGHT_MAKE_PDF_BIN = writeStub(
			`#!/usr/bin/env bash\necho "no renderer available" 1>&2\nexit 3\n`,
		);
		await expect(makePdf({ markdown: "# Hi" })).rejects.toThrow(/no renderer available/);
	});

	test("passes an outName resolved inside the creative folder to --out", async () => {
		// Stub echoes back the --out value it received so we can assert resolution.
		process.env.EIGHT_MAKE_PDF_BIN = writeStub(
			`#!/usr/bin/env bash\n` +
				`out=""\n` +
				`while [ $# -gt 0 ]; do\n` +
				`  if [ "$1" = "--out" ]; then out="$2"; shift; fi\n` +
				`  shift\n` +
				`done\n` +
				`echo "$out"\n`,
		);
		const result = await makePdf({ markdown: "# Hi", outName: "custom-report" });
		expect(result.path).toBe(path.join(CREATIVE_DIR, "custom-report.pdf"));
	});

	test("rejects when the configured binary does not exist", async () => {
		process.env.EIGHT_MAKE_PDF_BIN = path.join(tmpDir, "does-not-exist");
		await expect(makePdf({ markdown: "# Hi" })).rejects.toThrow(/not found/);
	});
});

describe("resolveMakePdfBin", () => {
	test("honours the env override", () => {
		expect(resolveMakePdfBin()).toBe(stubBin);
	});

	test("falls back to the default fleet-wide binary path", () => {
		delete process.env.EIGHT_MAKE_PDF_BIN;
		expect(resolveMakePdfBin()).toBe(DEFAULT_MAKE_PDF_BIN);
		expect(DEFAULT_MAKE_PDF_BIN).toContain(path.join(".8gent", "bin", "make-pdf"));
	});
});

// Integration: only runs when the real renderer is installed on this host.
describe("makePdf (real CLI integration)", () => {
	const realBin = DEFAULT_MAKE_PDF_BIN;
	const hasReal = fs.existsSync(realBin);
	const maybe = hasReal ? test : test.skip;

	maybe(
		"produces a real PDF file in the creative folder",
		async () => {
			delete process.env.EIGHT_MAKE_PDF_BIN; // use the real default binary
			const result = await makePdf({
				markdown: "# make_pdf test\n\nGenerated by the unit test.",
				title: "make_pdf unit test",
			});
			expect(result.kind).toBe("document");
			expect(result.path.startsWith(CREATIVE_DIR)).toBe(true);
			expect(fs.existsSync(result.path)).toBe(true);
		},
		30_000,
	);
});
