/**
 * The 8gent figure-8 mark, drawn from maths rather than letters.
 *
 * A TypeScript port of the design source ~/.8gent/evidence/hud-design/mark/mark8.py
 * (Moira, 8DO). The geometry is one continuous closed curve: a Bernoulli
 * lemniscate turned upright, so the bowls are round and the two strokes cross
 * in a clean X at the waist. The top bowl is scaled to 80% so it reads as a
 * numeral, not an infinity sign on its side.
 *
 * One rendering, braille: each cell is a 2x4 dot grid and a dot is lit when
 * it lies on the stroke. Every size uses it, the intro included. The earlier
 * half-block intro mark read as pixel art ("blocky"), so it is gone (#3159).
 *
 * Nothing here runs at launch. The cells are precomputed into mark8-cells.ts
 * by running this file:
 *
 *     bun apps/tui/src/lib/mark8.ts > apps/tui/src/lib/mark8-cells.ts
 *
 * and a test fails if that file drifts from the maths.
 */

/** Amber at the top of the stroke, orange at the bottom (BRAND.md). */
export const MARK_TOP = "#F07A28";
export const MARK_BOTTOM = "#E8610A";

type Point = readonly [number, number];

/**
 * The upright 8 in unit space, y in [-1, 1], as `n` points along the curve.
 * Lemniscate of Bernoulli rotated upright; points in the top bowl (y < 0) are
 * scaled by `topScale`, then the whole curve is renormalised to fill [-1, 1].
 */
export function curve(n = 6000, topScale = 0.8, xStretch = 1.35): Point[] {
	const pts: [number, number][] = [];
	for (let i = 0; i < n; i++) {
		const t = (2 * Math.PI * i) / n;
		const d = 1 + Math.sin(t) ** 2;
		let y = -Math.cos(t) / d;
		let x = ((Math.sin(t) * Math.cos(t)) / d) * xStretch;
		if (y < 0) {
			x *= topScale;
			y *= topScale;
		}
		pts.push([x, y]);
	}
	let lo = Number.POSITIVE_INFINITY;
	let hi = Number.NEGATIVE_INFINITY;
	for (const [, y] of pts) {
		if (y < lo) lo = y;
		if (y > hi) hi = y;
	}
	const mid = (lo + hi) / 2;
	const half = (hi - lo) / 2;
	return pts.map(([x, y]) => [x / half, (y - mid) / half] as const);
}

/**
 * Distance, in pixels, from any point of a w x h canvas to the curve. The mark
 * spans the canvas height less an 8% margin, centred. Points are bucketed on
 * a 4 px grid and only the 5x5 neighbourhood is searched, as in the source.
 */
export function distanceField(pts: readonly Point[], w: number, h: number): (px: number, py: number) => number {
	const margin = 0.08;
	const scale = (h / 2) * (1 - margin);
	const cx = w / 2;
	const cy = h / 2;
	const B = 4;
	const grid = new Map<string, Point[]>();
	for (const [ux, uy] of pts) {
		const x = cx + ux * scale;
		const y = cy + uy * scale;
		const key = `${Math.floor(x / B)},${Math.floor(y / B)}`;
		let bucket = grid.get(key);
		if (!bucket) {
			bucket = [];
			grid.set(key, bucket);
		}
		bucket.push([x, y]);
	}
	return (px, py) => {
		const gx = Math.floor(px / B);
		const gy = Math.floor(py / B);
		let best = 1e9;
		for (let dx = -2; dx <= 2; dx++) {
			for (let dy = -2; dy <= 2; dy++) {
				const bucket = grid.get(`${gx + dx},${gy + dy}`);
				if (!bucket) continue;
				for (const [x, y] of bucket) {
					const d = (x - px) ** 2 + (y - py) ** 2;
					if (d < best) best = d;
				}
			}
		}
		return Math.sqrt(best);
	};
}

const BRAILLE_DOTS: readonly (readonly [number, number, number])[] = [
	[0, 0, 0x01],
	[0, 1, 0x02],
	[0, 2, 0x04],
	[1, 0, 0x08],
	[1, 1, 0x10],
	[1, 2, 0x20],
	[0, 3, 0x40],
	[1, 3, 0x80],
];

/** A braille mark `cols` x `rows` cells; unlit cells are spaces. */
export function brailleRows(cols: number, rows: number, stroke: number, topScale = 0.8): string[] {
	const f = distanceField(curve(6000, topScale), cols * 2, rows * 4);
	const out: string[] = [];
	for (let r = 0; r < rows; r++) {
		let line = "";
		for (let c = 0; c < cols; c++) {
			let v = 0;
			for (const [dx, dy, bit] of BRAILLE_DOTS) {
				if (f(c * 2 + dx + 0.5, r * 4 + dy + 0.5) <= stroke / 2) v |= bit;
			}
			line += v ? String.fromCodePoint(0x2800 + v) : " ";
		}
		out.push(line);
	}
	return out;
}

/**
 * The sizes the TUI uses. The intro sizes step down with the terminal height;
 * strokes shrink with size so the bowls stay open. The header size is the
 * reference braille 8 from mark8.py (4 x 3, stroke 1.3).
 */
export const BRAILLE_INTRO_SIZES = [
	{ id: "large", cols: 18, rows: 12, stroke: 2.1 },
	{ id: "medium", cols: 14, rows: 9, stroke: 2.0 },
	{ id: "small", cols: 9, rows: 6, stroke: 1.7 },
] as const;

export const BRAILLE_SIZE = { id: "header", cols: 4, rows: 3, stroke: 1.3 } as const;

/** The formatter's line width (biome.json), so the generated file is already formatted. */
const LINE_WIDTH = 100;

/** Source text of mark8-cells.ts. */
export function generateCellsModule(): string {
	const lines: string[] = [
		"// Generated by `bun apps/tui/src/lib/mark8.ts > apps/tui/src/lib/mark8-cells.ts`.",
		"// Do not edit by hand: mark8.test.ts fails if this drifts from the maths in mark8.ts.",
		"",
		"/** Intro sizes, braille, keyed by size id. */",
		"export const MARK_INTRO: Readonly<Record<\"large\" | \"medium\" | \"small\", readonly string[]>> = {",
	];
	for (const s of BRAILLE_INTRO_SIZES) {
		const b = brailleRows(s.cols, s.rows, s.stroke);
		// Print it the way the formatter does: one line when it fits.
		const one = `\t${s.id}: [${b.map((r) => JSON.stringify(r)).join(", ")}],`;
		if (one.replace("\t", "  ").length <= LINE_WIDTH) {
			lines.push(one);
			continue;
		}
		lines.push(`\t${s.id}: [`);
		for (const row of b) lines.push(`\t\t${JSON.stringify(row)},`);
		lines.push("\t],");
	}
	lines.push("};");
	lines.push("");
	const b = brailleRows(BRAILLE_SIZE.cols, BRAILLE_SIZE.rows, BRAILLE_SIZE.stroke);
	lines.push("/** Header and spinner size, braille. */");
	lines.push(`export const MARK_HEADER: readonly string[] = [${b.map((r) => JSON.stringify(r)).join(", ")}];`);
	lines.push("");
	return lines.join("\n");
}

if (import.meta.main) {
	process.stdout.write(generateCellsModule());
}
