// Generated by `bun apps/tui/src/lib/mark8.ts > apps/tui/src/lib/mark8-cells.ts`.
// Do not edit by hand: mark8.test.ts fails if this drifts from the maths in mark8.ts.

/** Intro sizes, braille, keyed by size id. */
export const MARK_INTRO: Readonly<Record<"large" | "medium" | "small", readonly string[]>> = {
	large: [
		"     ⣀⣤⡶⠶⠶⢶⣤⣀     ",
		"    ⣼⠏⠁    ⠈⠹⣧    ",
		"    ⣿        ⣿    ",
		"    ⠹⣦      ⣴⠏    ",
		"     ⠘⠷⣦⡀⢀⣴⠾⠃     ",
		"       ⣨⡿⢿⣅       ",
		"    ⢀⣴⠟⠋  ⠙⠻⣦⡀    ",
		"   ⢠⡿⠁      ⠈⢿⡄   ",
		"  ⢠⡿          ⢿⡄  ",
		"  ⠸⣧          ⣼⠇  ",
		"   ⠹⣧⣀      ⣀⣼⠏   ",
		"    ⠈⠙⠛⠶⠶⠶⠶⠛⠋⠁    ",
	],
	medium: [
		"   ⢀⣤⠶⠞⠳⠶⣤⡀   ",
		"   ⣾⠁    ⠈⣷   ",
		"   ⢻⣆    ⣰⡟   ",
		"    ⠙⢷⣄⣠⡾⠋    ",
		"    ⣠⡴⠟⠻⢦⣄    ",
		"  ⢀⣾⠋    ⠙⣷⡀  ",
		"  ⣾⠃      ⠘⣷  ",
		"  ⢹⣆      ⣰⡏  ",
		"   ⠙⠻⠶⢦⡴⠶⠟⠋   ",
	],
	small: ["  ⣴⠞⠛⠳⣦  ", " ⠈⣧   ⣼⠁ ", "  ⠈⢳⣶⡞⠁  ", " ⢀⡾⠋ ⠙⢷⡀ ", " ⣾     ⣷ ", " ⠘⠳⢤⣤⡤⠞⠃ "],
};

/** Header and spinner size, braille. */
export const MARK_HEADER: readonly string[] = ["⢰⡋⢙⡆", "⢀⠽⠯⡀", "⠻⣄⣠⠟"];
