/**
 * The economic claim, measured rather than asserted.
 *
 * A SlideSpec is meant to be near-zero-token: the officer names an INTENT, a
 * LAYOUT and CLAIM REFERENCES, and code composes the actual slide. This file
 * measures a marker against the same slide expressed as the prose an officer
 * would otherwise have to write for the same information to reach James, and
 * asserts the marker is cheaper.
 *
 * Tokenisation uses the same deliberately crude ~4-chars-per-token estimate the
 * floor's own budget guard uses (packages/table/floor.ts::estimateTokens). It is
 * not a billing figure and is not claimed to be one; it is a consistent ruler
 * applied to both sides of the comparison.
 */

import { describe, expect, it } from "bun:test";
import { estimateTokens } from "../floor";
import { findSlideMarker, resolveSlide, type SlideSpec } from "../slide-spec";

interface Case {
	name: string;
	/** What the officer emits: prose it would say ALOUD anyway, plus a marker. */
	marker: string;
	/**
	 * The counterfactual: the same slide's information written as prose,
	 * because without a slide the officer must SAY every number and every
	 * label for it to reach James at all.
	 */
	prose: string;
}

const CASES: Case[] = [
	{
		name: "metric",
		marker:
			'[[SLIDE {"layout":"metric","heading":"Turns baked tonight","metric":{"value":"[[CLAIM src=dir.count path=~/.8gent/huddles glob=*]]","label":"huddles on disk"}}]]',
		prose:
			"Here is the number that matters. We baked a set of huddles tonight, and the count of huddle directories currently on disk under the 8gent huddles folder is the figure I want on the record, because it is the only measure of how many sessions actually completed end to end rather than merely starting.",
	},
	{
		name: "bullets",
		marker:
			'[[SLIDE {"layout":"bullets","heading":"What is still missing","bullets":["Stage pane in the Flow app","Dictation capture button","Speculative pre-render"]}]]',
		prose:
			"There are three things still missing before this ships. The first is the stage pane inside the Flow desktop app. The second is the dictation capture button that lets James start recording. The third is speculative pre-rendering so the next slide is ready before the floor moves.",
	},
	{
		name: "compare",
		marker: '[[SLIDE {"layout":"compare","heading":"Live versus baked","compare":{"left":"Live stage, one window","right":"Baked deck, one file"}}]]',
		prose:
			"The comparison I want to draw is between the live stage and the baked deck. On one side you have the live stage, which is one window that never reloads and grows as the huddle runs. On the other side you have the baked deck, which is a single file you can watch afterwards from your phone.",
	},
];

describe("token cost of a slide", () => {
	it("a marker costs meaningfully fewer tokens than the same slide as prose", () => {
		const rows: string[] = [];
		for (const c of CASES) {
			const markerTokens = estimateTokens(c.marker);
			const proseTokens = estimateTokens(c.prose);
			rows.push(
				`  ${c.name.padEnd(8)} marker ~${String(markerTokens).padStart(3)} tok   prose ~${String(proseTokens).padStart(3)} tok   ` +
					`saving ${(((proseTokens - markerTokens) / proseTokens) * 100).toFixed(0)}%`,
			);
			expect(markerTokens).toBeLessThan(proseTokens);
		}
		console.log(`\nMeasured slide token cost (~4 chars/token, same ruler both sides):\n${rows.join("\n")}\n`);
	});

	it("a slide marker stays inside a small fixed budget", () => {
		// The point of the design is that a slide is CHEAP and BOUNDED. If a
		// marker ever costs more than this, the schema has grown a field that
		// carries rendered content instead of a reference, and the "near-zero
		// token" claim is no longer true.
		for (const c of CASES) expect(estimateTokens(c.marker)).toBeLessThan(60);
	});

	it("a claim reference costs the officer nothing to be precise", () => {
		// A reference is roughly the cost of the sentence it replaces, but the
		// VALUE it resolves to was never generated by the model at all - so the
		// completion tokens spent on the number are exactly zero, at any
		// precision. That is the actual saving, and it is structural.
		const spec = resolveSlide(CASES[0].marker).spec as SlideSpec;
		expect(spec.metric?.value).toContain("[[CLAIM");
		expect(spec.metric?.value).not.toMatch(/^\d+$/);
	});

	it("the marker is a strict addition to speech the officer makes anyway", () => {
		// The honest accounting: an officer speaking in a huddle emits its spoken
		// line either way. The slide's MARGINAL cost is the marker alone.
		const reply = `We are close, but the stage pane is not wired yet.\n\n${CASES[1].marker}`;
		const speech = resolveSlide(reply).speech;
		const marginal = estimateTokens(reply) - estimateTokens(speech);
		expect(marginal).toBeLessThan(60);
		console.log(`  marginal cost of adding a slide to a spoken turn: ~${marginal} tokens\n`);
	});

	it("zen-gen slides cost zero model tokens", async () => {
		// Not an estimate: the zen path never calls a model, so there is no
		// prompt and no completion to count. Asserted structurally.
		const source = await Bun.file(new URL("../zen.ts", import.meta.url)).text();
		expect(source).not.toContain("fetch(");
		expect(findSlideMarker(source)).toBeNull();
	});
});
