"""
Phase 0 verification: load the trained checkpoint, run sample inference,
measure latency, write a structured verification report.

Run after training completes:
  python3 packages/eight-bdh/trainer/local/verify_phase_0.py

Outputs:
  - packages/eight-bdh/trainer/local/phase-0-verify-report.json
  - prints a human-readable summary

Heartbeat ship-gate criteria (spec section 9 Phase 0):
  - Trains end-to-end                : checkpoint exists at expected path
  - <100ms inference latency on M2   : measured below
  - 70% accuracy on toy holdout       : NOT GATED in Phase 0 because
                                        no labeled holdout exists; the
                                        eval harness is a Phase 1 prereq
                                        per the boardroom decision.
"""

import json
import os
import sys
import time
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[4]
BDH_REPO = Path.home() / "8gent-bdh"
CHECKPOINT_PATH = REPO_ROOT / "packages" / "eight-bdh" / "checkpoints" / "phase-0-5m.pt"
LOG_DIR = REPO_ROOT / "packages" / "eight-bdh" / "trainer" / "local"
TRAIN_LOG = LOG_DIR / "phase-0-train-log.json"
REPORT_PATH = LOG_DIR / "phase-0-verify-report.json"

sys.path.insert(0, str(BDH_REPO))

import torch
from bdh import BDH, BDHConfig

# ── Device ──────────────────────────────────────────────────────────────

def select_device():
    if torch.cuda.is_available():
        return torch.device("cuda")
    if torch.backends.mps.is_available() and torch.backends.mps.is_built():
        return torch.device("mps")
    return torch.device("cpu")

DEVICE = select_device()
print(f"[verify] device={DEVICE}", flush=True)

# ── Sanity ──────────────────────────────────────────────────────────────

if not CHECKPOINT_PATH.exists():
    print(f"[error] checkpoint not found at {CHECKPOINT_PATH}", file=sys.stderr)
    sys.exit(1)

print(f"[verify] loading checkpoint {CHECKPOINT_PATH.name}", flush=True)
ckpt = torch.load(CHECKPOINT_PATH, map_location=DEVICE, weights_only=False)
cfg_d = ckpt["config"]
cfg = BDHConfig(
    n_layer=cfg_d["n_layer"],
    n_embd=cfg_d["n_embd"],
    n_head=cfg_d["n_head"],
    mlp_internal_dim_multiplier=cfg_d["mlp_internal_dim_multiplier"],
    dropout=cfg_d["dropout"],
    vocab_size=cfg_d["vocab_size"],
)
model = BDH(cfg).to(DEVICE)
model.load_state_dict(ckpt["model_state_dict"])
model.eval()
n_params = sum(p.numel() for p in model.parameters())
print(f"[verify] model loaded: {n_params/1e6:.2f}M params", flush=True)

# ── Sample inference prompts ────────────────────────────────────────────

# Each prompt is a partial JSON state. We measure how the trained model
# completes them. With a rule-based corpus, the model should produce
# structurally-valid JSON continuations even if the routing semantics
# are not meaningful.

prompts = [
    '{"id":"verify-1","state":{"request":"rewrite this auth middleware to use the new policy engine","context":{',
    '{"id":"verify-2","state":{"request":"what files changed in the last commit","context":{"tools_available":["Read","Bash"],',
    '{"id":"verify-3","state":{"request":"deploy to production","context":{"vessels_available":["8DO","8SO"],',
    '{"id":"verify-4","state":{"request":"summarise the project status","context":{"history_summary":"fresh session, no prior turns","budget_remaining":{',
    '{"id":"verify-5","state":{"request":"add a darkmode toggle to the settings panel","context":{"tools_available":["Edit","Read"],"vessels_available":["8DO"],',
]

# ── Latency measurement ─────────────────────────────────────────────────

# Heartbeat target: <100ms per decision on M2 Max
# A "decision" is roughly 30-80 generated bytes worth of output for the
# decision JSON head. We measure time-to-first-100-tokens as a proxy.

print(f"[verify] running {len(prompts)} sample completions", flush=True)

samples = []
latency_ms_per_token = []

for i, prompt in enumerate(prompts, 1):
    prompt_bytes = prompt.encode("utf-8")
    idx = torch.tensor([list(prompt_bytes)], dtype=torch.long, device=DEVICE)

    # Warm up GPU on first prompt
    if i == 1:
        with torch.no_grad():
            _ = model.generate(idx, max_new_tokens=10, temperature=0.8)

    t0 = time.time()
    with torch.no_grad():
        out_idx = model.generate(idx, max_new_tokens=120, temperature=0.8, top_k=40)
    elapsed_ms = (time.time() - t0) * 1000

    new_bytes = out_idx[0, idx.shape[1]:].tolist()
    out_text = bytes(new_bytes).decode("utf-8", errors="replace")
    ms_per_tok = elapsed_ms / max(len(new_bytes), 1)
    latency_ms_per_token.append(ms_per_tok)

    samples.append({
        "prompt_id": f"verify-{i}",
        "prompt": prompt,
        "completion": out_text,
        "tokens_generated": len(new_bytes),
        "total_ms": round(elapsed_ms, 1),
        "ms_per_token": round(ms_per_tok, 2),
    })
    print(
        f"[verify] sample {i}/{len(prompts)}: "
        f"{len(new_bytes)} tokens in {elapsed_ms:.1f}ms "
        f"({ms_per_tok:.2f}ms/tok)",
        flush=True,
    )

# ── Latency summary ─────────────────────────────────────────────────────

avg_ms_per_tok = sum(latency_ms_per_token) / len(latency_ms_per_token)
# Approximate per-decision latency: a Decision JSON is ~80 bytes head
proxy_decision_ms = avg_ms_per_tok * 80
heartbeat_target_ms = 100

print(f"[verify] avg ms per token = {avg_ms_per_tok:.2f}", flush=True)
print(
    f"[verify] proxy per-decision latency = {proxy_decision_ms:.1f}ms "
    f"(target <{heartbeat_target_ms}ms)",
    flush=True,
)

# ── Training log integration ────────────────────────────────────────────

train_log = None
if TRAIN_LOG.exists():
    with TRAIN_LOG.open() as fh:
        train_log = json.load(fh)
    final_train = train_log["loss_curve_train"][-1] if train_log["loss_curve_train"] else None
    final_val = train_log["loss_curve_val"][-1] if train_log["loss_curve_val"] else None
    print(
        f"[verify] training: {train_log['n_examples']} examples, "
        f"{train_log['train_seconds']/60:.1f} min, "
        f"final_train={final_train[1] if final_train else None}, "
        f"final_val={final_val[1] if final_val else None}",
        flush=True,
    )

# ── Heartbeat gate ──────────────────────────────────────────────────────

heartbeat_gates = {
    "trains_end_to_end": CHECKPOINT_PATH.exists(),
    "loss_descended": (
        train_log is not None
        and len(train_log["loss_curve_train"]) > 1
        and train_log["loss_curve_train"][-1][1] < train_log["loss_curve_train"][0][1]
    ),
    "val_loss_under_one": (
        train_log is not None
        and train_log["best_val_loss"] is not None
        and train_log["best_val_loss"] < 1.0
    ),
    "inference_works": all(s["tokens_generated"] > 0 for s in samples),
    "latency_under_target": proxy_decision_ms < heartbeat_target_ms,
}

all_gates_pass = all(heartbeat_gates.values())

print("[verify] heartbeat gates:", flush=True)
for gate, passed in heartbeat_gates.items():
    flag = "PASS" if passed else "FAIL"
    print(f"  {flag}  {gate}", flush=True)
print(f"[verify] overall: {'PASS' if all_gates_pass else 'FAIL'}", flush=True)

# ── Write report ────────────────────────────────────────────────────────

report = {
    "phase": 0,
    "status": "PASS" if all_gates_pass else "FAIL",
    "model_id": ckpt.get("model_id", "8gent-0.1.0-bdh-r:5m"),
    "device": str(DEVICE),
    "params_millions": n_params / 1e6,
    "config": cfg_d,
    "training": ckpt.get("training", {}),
    "heartbeat_gates": heartbeat_gates,
    "latency": {
        "avg_ms_per_token": round(avg_ms_per_tok, 2),
        "proxy_per_decision_ms": round(proxy_decision_ms, 1),
        "target_ms": heartbeat_target_ms,
    },
    "samples": samples,
}

with REPORT_PATH.open("w") as fh:
    json.dump(report, fh, indent=2)

print(f"[verify] wrote report to {REPORT_PATH.relative_to(REPO_ROOT)}", flush=True)
sys.exit(0 if all_gates_pass else 2)
