/**
 * Agent handoff protocol (issue #2422).
 *
 * Per Rob Pike: simple beats complex. Every orchestration hop is a failure
 * point. This module enforces a flat, single-level delegation pattern.
 *
 *   Agent A --(handoff)--> Agent B
 *   Agent B MUST complete or fail. Agent B CANNOT issue further handoffs.
 *
 * Backwards-compat: the existing `DispatchRouter` (cross-surface) and the
 * `cos-router` `/delegate` flow keep working. This is the canonical path
 * for agent-to-agent delegation that needs depth enforcement, audit, and
 * timeouts.
 */

import { randomUUID } from "node:crypto";
import {
	type HandoffAuditLog,
	type HandoffAuditRecord,
} from "./audit/handoff-log";

export type HandoffPriority = "critical" | "high" | "normal" | "low";

export type HandoffStatus = "completed" | "failed" | "timeout" | "rejected";

/** Typed envelope for one agent-to-agent delegation. */
export interface AgentHandoff {
	/** Unique id. Generated by `createHandoff` if you don't supply one. */
	id: string;
	/** Source agent or officer (e.g. "8EO", "agent_xyz"). */
	from: string;
	/** Target agent or officer. */
	to: string;
	/** What the target should do. Imperative, single-paragraph. */
	task: string;
	/** Compressed relevant context. Keep small; this is not a memory dump. */
	context_summary: string;
	/** What success looks like. Used for self-grading and audit review. */
	expected_output: string;
	/** Hard timeout. Defaults to dispatcher's `defaultTimeoutMs` if absent. */
	deadline_ms?: number;
	/** File paths or entity names that must travel with the handoff. */
	artifacts: string[];
	/** Triage hint for the executor. */
	priority: HandoffPriority;
}

/** Result returned by the target agent (or synthesized on timeout/rejection). */
export interface HandoffResult {
	handoff_id: string;
	status: HandoffStatus;
	output: string;
	artifacts_produced: string[];
	tokens_used: number;
	duration_ms: number;
	error?: string;
}

/**
 * Function signature an executor implements. The dispatcher calls this
 * to actually run the work. Wrap your AgentPool, vessel mesh, or test
 * fake behind this contract.
 */
export type HandoffExecutor = (
	handoff: AgentHandoff,
	signal: AbortSignal,
) => Promise<HandoffResult>;

export interface HandoffDispatcherOptions {
	executor: HandoffExecutor;
	auditLog: HandoffAuditLog;
	/** Default timeout when a handoff omits `deadline_ms`. */
	defaultTimeoutMs?: number;
	/**
	 * Max delegation depth. 1 = flat: root issues, target completes, no
	 * further nesting. Nested handoff at depth >= maxDepth is rejected.
	 */
	maxDepth?: number;
}

/**
 * Build an AgentHandoff with sensible defaults. The id and `artifacts: []`
 * are auto-filled if you don't supply them. Use this from agent code so
 * you don't end up with handoffs missing required fields.
 */
export function createHandoff(input: Omit<Partial<AgentHandoff>, "id"> & {
	from: string;
	to: string;
	task: string;
}): AgentHandoff {
	return {
		id: `handoff_${Date.now().toString(36)}_${randomUUID().slice(0, 8)}`,
		from: input.from,
		to: input.to,
		task: input.task,
		context_summary: input.context_summary ?? "",
		expected_output: input.expected_output ?? "",
		deadline_ms: input.deadline_ms,
		artifacts: input.artifacts ?? [],
		priority: input.priority ?? "normal",
	};
}

/**
 * The dispatcher. Stateless except for the in-flight depth tracker.
 *
 * Depth tracking lives here, not on the handoff itself, because depth is
 * a property of the call tree at runtime - the envelope shouldn't carry
 * a number that callers can lie about. When `dispatch` is invoked from
 * inside another handoff's executor, the caller passes `parentId` and the
 * dispatcher walks the in-flight map to compute true depth.
 */
export class HandoffDispatcher {
	private readonly executor: HandoffExecutor;
	private readonly auditLog: HandoffAuditLog;
	private readonly defaultTimeoutMs: number;
	private readonly maxDepth: number;
	private readonly inFlight = new Map<string, { depth: number; parentId: string | null }>();

	constructor(opts: HandoffDispatcherOptions) {
		this.executor = opts.executor;
		this.auditLog = opts.auditLog;
		this.defaultTimeoutMs = opts.defaultTimeoutMs ?? 5 * 60 * 1000;
		this.maxDepth = opts.maxDepth ?? 1;
	}

	/**
	 * Issue a handoff. `parentId` is set automatically when the dispatcher
	 * recurses (executor calls back in). Callers from outside the call
	 * tree leave it null.
	 */
	async dispatch(
		handoff: AgentHandoff,
		opts: { parentId?: string | null } = {},
	): Promise<HandoffResult> {
		const parentId = opts.parentId ?? null;
		const parentEntry = parentId ? this.inFlight.get(parentId) : null;
		const depth = parentEntry ? parentEntry.depth + 1 : 0;

		if (depth >= this.maxDepth) {
			const result: HandoffResult = {
				handoff_id: handoff.id,
				status: "rejected",
				output: "",
				artifacts_produced: [],
				tokens_used: 0,
				duration_ms: 0,
				error: `delegation depth ${depth} exceeds max ${this.maxDepth}; flat dispatch only`,
			};
			this.persistAudit({
				handoff,
				result,
				depth,
				parentId,
				startedAt: Date.now(),
				completedAt: Date.now(),
			});
			return result;
		}

		const startedAt = Date.now();
		const timeoutMs = handoff.deadline_ms ?? this.defaultTimeoutMs;
		const controller = new AbortController();
		this.inFlight.set(handoff.id, { depth, parentId });

		let timer: ReturnType<typeof setTimeout> | null = null;
		const timeoutPromise = new Promise<HandoffResult>((resolve) => {
			timer = setTimeout(() => {
				controller.abort();
				resolve({
					handoff_id: handoff.id,
					status: "timeout",
					output: "",
					artifacts_produced: [],
					tokens_used: 0,
					duration_ms: Date.now() - startedAt,
					error: `handoff to ${handoff.to} exceeded ${timeoutMs}ms`,
				});
			}, timeoutMs);
		});

		let result: HandoffResult;
		try {
			result = await Promise.race([
				this.executor(handoff, controller.signal).then((r) => ({
					...r,
					handoff_id: handoff.id,
					duration_ms: r.duration_ms || Date.now() - startedAt,
				})),
				timeoutPromise,
			]);
		} catch (err) {
			result = {
				handoff_id: handoff.id,
				status: "failed",
				output: "",
				artifacts_produced: [],
				tokens_used: 0,
				duration_ms: Date.now() - startedAt,
				error: err instanceof Error ? err.message : String(err),
			};
		} finally {
			if (timer) clearTimeout(timer);
			this.inFlight.delete(handoff.id);
		}

		this.persistAudit({
			handoff,
			result,
			depth,
			parentId,
			startedAt,
			completedAt: Date.now(),
		});

		return result;
	}

	/** Snapshot of in-flight handoffs. Useful for ops dashboards. */
	listInFlight(): Array<{ id: string; depth: number; parentId: string | null }> {
		const out: Array<{ id: string; depth: number; parentId: string | null }> = [];
		for (const [id, entry] of this.inFlight) {
			out.push({ id, depth: entry.depth, parentId: entry.parentId });
		}
		return out;
	}

	private persistAudit(entry: HandoffAuditRecord): void {
		try {
			this.auditLog.record(entry);
		} catch (err) {
			console.warn(
				`[handoff] audit log write failed: ${err instanceof Error ? err.message : err}`,
			);
		}
	}
}
