/**
 * Task artifacts - when an officer makes a thing, it becomes a thing.
 *
 * James asked Rishi for a diagram of an agent vessel. The task ran on his codex
 * harness, succeeded, and posted 1004 characters of raw mermaid source into a
 * chat bubble, truncated mid-token at "Agent --> Ar". He asked "where is it?"
 * and then "i dont see the diagram yet". He never got a diagram, because the
 * system had nowhere to put one.
 *
 * The gap was never capability - the harness did the work. It was that a
 * DELIVERABLE was being returned as a CHAT MESSAGE. So:
 *
 *   1. Every approved task gets its own directory under ~/.8gent/creative/tasks.
 *   2. The worker is TOLD, in the prompt, to write deliverables there. Not an
 *      environment variable: helm builds a fixed minimal env with no per-spawn
 *      passthrough, and an env var an LLM never reads does nothing anyway. The
 *      instruction has to be in words the harness will act on.
 *   3. Afterwards the daemon scans that ONE directory. Declared, not guessed -
 *      it never sniffs stdout trying to decide whether something was a file.
 *   4. Renderable source (mermaid, svg, dot, html) is rendered to PNG, and BOTH
 *      files are kept: the source stays editable and diffable, the render is
 *      what you open.
 *   5. The full worker log is always written to disk, so the channel post can
 *      stay short without the remainder becoming unreachable.
 *
 * ~/.8gent/creative is deliberate rather than a new location: Creative.swift
 * already scans it for png/jpg/gif/mp4 and the huddle bake already writes there.
 * Task output was the only producer that did not, so this connects a producer to
 * a surface that was already running.
 */

import { spawnSync } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { slideToPng } from "./bake";

/** Where the Creative gallery already looks. */
export const CREATIVE_DIR = path.join(os.homedir(), ".8gent", "creative");
export const TASKS_DIR = path.join(CREATIVE_DIR, "tasks");

/** Source formats worth rendering. Everything else is kept as-is. */
const RENDERABLE = new Set([".mmd", ".mermaid", ".svg", ".dot", ".gv", ".html", ".htm"]);

/** What the Creative gallery can already display without any change to it. */
const VIEWABLE = new Set([".png", ".jpg", ".jpeg", ".gif", ".mp4", ".mov"]);

/** Never treat our own bookkeeping as a deliverable. */
const RESERVED = new Set(["output.log", "render.log"]);

export interface Artifact {
	/** Absolute path, so a channel post can name something openable. */
	path: string;
	name: string;
	bytes: number;
	/** True when this file was produced by rendering another one. */
	rendered: boolean;
	/** For a render, the source it came from. */
	from?: string;
}

export function artifactDirFor(token: string): string {
	// Token is generated by stagePending and is [A-Z0-9]{4,12}, but this path is
	// built from it, so it is validated rather than trusted.
	const safe = token.replace(/[^A-Za-z0-9_-]/g, "").slice(0, 24) || "untokened";
	return path.join(TASKS_DIR, safe);
}

/** Create the drop directory. Safe to call twice. */
export function prepareArtifactDir(token: string): string {
	const dir = artifactDirFor(token);
	fs.mkdirSync(dir, { recursive: true });
	return dir;
}

/**
 * The sentence appended to an approved task's prompt.
 *
 * Deliberately short and imperative. A long preamble gets ignored by a 9B model,
 * and this has to survive being the last thing in a prompt that already carries
 * the actual instruction.
 */
export function artifactInstruction(dir: string): string {
	return [
		"",
		`When you produce a FILE (a diagram, document, image, dataset, deck), write it to ${dir}`,
		"and say the filename. Do not paste a large file's contents into your reply.",
		"For a diagram, write mermaid to a .mmd file there - it will be rendered to an image.",
	].join("\n");
}

/** Write the worker's full output next to its artifacts, always. */
export function writeFullLog(token: string, output: string): string | null {
	try {
		const dir = prepareArtifactDir(token);
		const p = path.join(dir, "output.log");
		fs.writeFileSync(p, output, "utf8");
		return p;
	} catch {
		return null;
	}
}

/** A self-contained page that renders one mermaid graph, offline. */
function mermaidPage(source: string, mermaidJs: string): string {
	// The source is injected as a TEXT NODE via textContent, never as markup, and
	// mermaid reads it from there. Model output must never become HTML.
	return `<!doctype html><html><head><meta charset="utf-8"><style>
body{margin:0;background:#0A0908;display:flex;align-items:center;justify-content:center;
  min-height:100vh;font-family:-apple-system,BlinkMacSystemFont,"SF Pro Text",Helvetica,Arial,sans-serif}
#g{padding:48px}</style></head><body>
<pre id="src" style="display:none"></pre><div id="g"></div>
<script>${mermaidJs}</script>
<script>
document.getElementById("src").textContent = ${JSON.stringify(source)};
mermaid.initialize({startOnLoad:false,theme:"dark",securityLevel:"strict"});
mermaid.render("d", document.getElementById("src").textContent).then(function(r){
  document.getElementById("g").innerHTML = r.svg;
});
</script></body></html>`;
}

/** Locate a vendored mermaid bundle, if one has been installed. */
function findMermaidJs(): string | null {
	const candidates = [
		path.join(process.cwd(), "node_modules", "mermaid", "dist", "mermaid.min.js"),
		path.join(os.homedir(), "8gent-code", "node_modules", "mermaid", "dist", "mermaid.min.js"),
	];
	for (const c of candidates) {
		try {
			if (fs.existsSync(c)) return fs.readFileSync(c, "utf8");
		} catch {
			/* keep looking */
		}
	}
	return null;
}

function chromeBinary(): string | null {
	for (const c of [
		"/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
		"/Applications/Chromium.app/Contents/MacOS/Chromium",
	]) {
		if (fs.existsSync(c)) return c;
	}
	return null;
}

/**
 * Render one source file to a PNG beside it.
 *
 * Returns the png path, or null when it could not be rendered. A failure is
 * never fatal and never silent: the source file is still delivered, and the
 * caller says the render did not happen rather than pretending there was
 * nothing to render.
 */
export function renderToPng(srcPath: string): string | null {
	const chrome = chromeBinary();
	if (!chrome) return null;
	const ext = path.extname(srcPath).toLowerCase();
	const pngPath = `${srcPath.slice(0, -ext.length)}.png`;
	const dir = path.dirname(srcPath);

	try {
		if (ext === ".mmd" || ext === ".mermaid") {
			const lib = findMermaidJs();
			// No vendored mermaid: keep the source, skip the render, say nothing
			// false. Fetching a library at render time would put a network call in
			// the middle of a local-first path.
			if (!lib) return null;
			const html = path.join(dir, `.${path.basename(srcPath)}.render.html`);
			fs.writeFileSync(html, mermaidPage(fs.readFileSync(srcPath, "utf8"), lib), "utf8");
			const ok = slideToPng(html, pngPath, chrome);
			try {
				fs.rmSync(html, { force: true });
			} catch {
				/* best effort */
			}
			return ok ? pngPath : null;
		}
		if (ext === ".svg" || ext === ".html" || ext === ".htm") {
			// Chrome renders both directly from the file.
			return slideToPng(srcPath, pngPath, chrome) ? pngPath : null;
		}
		if (ext === ".dot" || ext === ".gv") {
			// Graphviz only if the user already has it; never installed on the fly.
			const r = spawnSync("dot", ["-Tpng", srcPath, "-o", pngPath], { timeout: 60_000 });
			return r.status === 0 && fs.existsSync(pngPath) ? pngPath : null;
		}
	} catch {
		return null;
	}
	return null;
}

/**
 * Everything the worker left in its directory, with renderable source rendered.
 *
 * Ordered so the thing a human wants to open comes first: renders and viewable
 * media, then sources, then anything else.
 */
export function collectArtifacts(token: string): Artifact[] {
	const dir = artifactDirFor(token);
	let names: string[] = [];
	try {
		names = fs.readdirSync(dir);
	} catch {
		return [];
	}

	const out: Artifact[] = [];
	const rendered = new Set<string>();

	for (const name of names) {
		if (RESERVED.has(name) || name.startsWith(".")) continue;
		const p = path.join(dir, name);
		let st: fs.Stats;
		try {
			st = fs.statSync(p);
		} catch {
			continue;
		}
		if (!st.isFile()) continue;

		const ext = path.extname(name).toLowerCase();
		if (RENDERABLE.has(ext)) {
			const png = renderToPng(p);
			if (png) {
				rendered.add(path.basename(png));
				try {
					out.push({
						path: png,
						name: path.basename(png),
						bytes: fs.statSync(png).size,
						rendered: true,
						from: name,
					});
				} catch {
					/* stat raced with a rewrite; the source below still lands */
				}
			}
		}
		out.push({ path: p, name, bytes: st.size, rendered: false });
	}

	// A png we just produced also appears in the directory listing; keep one copy.
	const seen = new Set<string>();
	const deduped = out.filter((a) => {
		if (seen.has(a.path)) return false;
		seen.add(a.path);
		return !(rendered.has(a.name) && !a.rendered);
	});

	const rank = (a: Artifact) =>
		a.rendered ? 0 : VIEWABLE.has(path.extname(a.name).toLowerCase()) ? 1 : 2;
	return deduped.sort((x, y) => rank(x) - rank(y) || x.name.localeCompare(y.name));
}

/** Human-readable size, because "148 KB" reads and "151552" does not. */
export function humanBytes(n: number): string {
	if (n < 1024) return `${n} B`;
	if (n < 1024 * 1024) return `${Math.round(n / 1024)} KB`;
	return `${(n / (1024 * 1024)).toFixed(1)} MB`;
}
