/**
 * Colour maths. Every constant here is transcribed from a primary source, and
 * the source is named at the constant, because a wrong digit in a matrix is a
 * bug nobody ever finds by looking at the output.
 *
 * Two colour spaces, two different jobs:
 *
 *   OKLCH is the AUTHORING space. Ramps are generated by moving L and C with H
 *   held fixed, which is the only way to get a lightness ramp that reads evenly.
 *   Source: Björn Ottosson, "A perceptual color space for image processing",
 *   https://bottosson.github.io/posts/oklab/
 *
 *   sRGB-derived HSL is the JUDGING space for the brand hue ban. BRAND.md says
 *   "Banned hues: 270-350 (purple, pink, violet, magenta)" and a designer saying
 *   that means the familiar colour-wheel degrees, not OKLCH hue angles - the two
 *   differ by up to ~30 degrees and banning the wrong band would let real violet
 *   through. So the ban is enforced on the hue of the colour AS RENDERED. There
 *   is no way to spoof it: whatever OKLCH triple you start from, it is converted
 *   to the sRGB pixel a human will actually see, and that pixel is judged.
 *
 * Contrast is WCAG 2.2, deliberately, and NOT APCA. Two honest reasons, both
 * documented in the README: (1) WCAG 2.x is the only contrast maths with legal
 * force (EN 301 549, Section 508, the EAA all point at it); APCA was removed
 * from the WCAG 3 draft in July 2023 and the April 2026 WCAG 3 Editor's Draft
 * still says the contrast algorithm is "yet to be determined". (2) The apca-w3
 * reference implementation ships under a "Limited W3 License" with patents
 * pending and restricted naming, which is not a licence this repo can take.
 * The advisory perceptual score is Oklab lightness difference, which is
 * unencumbered and which we do not call a contrast standard.
 */

export interface Rgb {
	/** 0-1, gamma-encoded sRGB. */
	r: number;
	g: number;
	b: number;
}

export interface Oklch {
	/** Perceptual lightness, 0-1. */
	l: number;
	/** Chroma, 0 to ~0.4 for in-gamut sRGB. */
	c: number;
	/** Hue angle in degrees, 0-360. */
	h: number;
}

// ---------------------------------------------------------------------------
// sRGB transfer functions. CSS Color 4 sample code (conversions.js). The
// sign-extension matters: gamut mapping produces negative components, and a
// non-extended transfer function turns them into NaN instead of a clamp.
// ---------------------------------------------------------------------------

const SRGB_DECODE_CUTOFF = 0.04045;
const SRGB_ENCODE_CUTOFF = 0.0031308;

function linearise(v: number): number {
	const sign = v < 0 ? -1 : 1;
	const abs = Math.abs(v);
	if (abs <= SRGB_DECODE_CUTOFF) return v / 12.92;
	return sign * ((abs + 0.055) / 1.055) ** 2.4;
}

function encode(v: number): number {
	const sign = v < 0 ? -1 : 1;
	const abs = Math.abs(v);
	if (abs > SRGB_ENCODE_CUTOFF) return sign * (1.055 * abs ** (1 / 2.4) - 0.055);
	return 12.92 * v;
}

// ---------------------------------------------------------------------------
// linear sRGB <-> Oklab. Ottosson's published float32 constants.
// ---------------------------------------------------------------------------

function linearRgbToOklab(r: number, g: number, b: number): [number, number, number] {
	const l = 0.4122214708 * r + 0.5363325363 * g + 0.0514459929 * b;
	const m = 0.2119034982 * r + 0.6806995451 * g + 0.1073969566 * b;
	const s = 0.0883024619 * r + 0.2817188376 * g + 0.6299787005 * b;
	// Math.cbrt, never Math.pow(x, 1/3): the latter is NaN for the negative LMS
	// values that occur whenever the source colour is outside sRGB.
	const l_ = Math.cbrt(l);
	const m_ = Math.cbrt(m);
	const s_ = Math.cbrt(s);
	return [
		0.2104542553 * l_ + 0.793617785 * m_ - 0.0040720468 * s_,
		1.9779984951 * l_ - 2.428592205 * m_ + 0.4505937099 * s_,
		0.0259040371 * l_ + 0.7827717662 * m_ - 0.808675766 * s_,
	];
}

function oklabToLinearRgb(L: number, a: number, b: number): [number, number, number] {
	const l_ = L + 0.3963377774 * a + 0.2158037573 * b;
	const m_ = L - 0.1055613458 * a - 0.0638541728 * b;
	const s_ = L - 0.0894841775 * a - 1.291485548 * b;
	const l = l_ * l_ * l_;
	const m = m_ * m_ * m_;
	const s = s_ * s_ * s_;
	return [
		4.0767416621 * l - 3.3077115913 * m + 0.2309699292 * s,
		-1.2684380046 * l + 2.6097574011 * m - 0.3413193965 * s,
		-0.0041960863 * l - 0.7034186147 * m + 1.707614701 * s,
	];
}

export function oklchToOklab(c: Oklch): [number, number, number] {
	const rad = (c.h * Math.PI) / 180;
	return [c.l, c.c * Math.cos(rad), c.c * Math.sin(rad)];
}

export function oklabToOklch(L: number, a: number, b: number): Oklch {
	const chroma = Math.sqrt(a * a + b * b);
	let hue = (Math.atan2(b, a) * 180) / Math.PI;
	if (hue < 0) hue += 360;
	// CSS Color 4's powerless-hue epsilon. Below it the hue is meaningless, and
	// reporting a made-up angle for a grey would corrupt the brand hue check.
	if (chroma <= 0.000004) hue = 0;
	return { l: L, c: chroma, h: hue };
}

// ---------------------------------------------------------------------------
// Gamut. sRGB's reference range is 0-1 on the GAMMA-ENCODED components, so the
// test and the clip both happen after encoding.
// ---------------------------------------------------------------------------

const GAMUT_TOLERANCE = 1e-5;

function toEncodedTriple(c: Oklch): [number, number, number] {
	const [L, a, b] = oklchToOklab(c);
	const lin = oklabToLinearRgb(L, a, b);
	return [encode(lin[0]), encode(lin[1]), encode(lin[2])];
}

export function inSrgbGamut(c: Oklch): boolean {
	const t = toEncodedTriple(c);
	return t.every((v) => v >= -GAMUT_TOLERANCE && v <= 1 + GAMUT_TOLERANCE);
}

/**
 * CSS Color 4 gamut mapping: binary search on chroma at constant lightness and
 * constant hue, stopping when the clipped colour is within one just-noticeable
 * difference (deltaEOK) of the reduced-chroma colour. JND = 0.02 and
 * epsilon = 0.0001 are both normative in css-color-4 section 14.2.
 *
 * Constant hue is the property that matters to us: a mapped colour never
 * migrates into a banned hue band, so gamut mapping can never smuggle purple in
 * through the back door. The brand check still runs afterwards regardless -
 * we do not rely on that argument, we test it.
 */
const JND = 0.02;
const GAMUT_EPSILON = 0.0001;

function clipToSrgb(c: Oklch): Rgb {
	const t = toEncodedTriple(c);
	return {
		r: Math.min(1, Math.max(0, t[0])),
		g: Math.min(1, Math.max(0, t[1])),
		b: Math.min(1, Math.max(0, t[2])),
	};
}

function deltaEOk(a: [number, number, number], b: [number, number, number]): number {
	return Math.hypot(a[0] - b[0], a[1] - b[1], a[2] - b[2]);
}

export function gamutMap(input: Oklch): Rgb {
	if (input.l >= 1) return { r: 1, g: 1, b: 1 };
	if (input.l <= 0) return { r: 0, g: 0, b: 0 };
	if (inSrgbGamut(input)) return clipToSrgb(input);

	let min = 0;
	let max = input.c;
	let minInGamut = true;
	let current: Oklch = { ...input };
	let clipped = clipToSrgb(current);

	const labOf = (rgb: Rgb) => linearRgbToOklab(linearise(rgb.r), linearise(rgb.g), linearise(rgb.b));

	if (deltaEOk(oklchToOklab(current), labOf(clipped)) < JND) return clipped;

	while (max - min > GAMUT_EPSILON) {
		const chroma = (min + max) / 2;
		current = { l: input.l, c: chroma, h: input.h };
		if (minInGamut && inSrgbGamut(current)) {
			min = chroma;
			continue;
		}
		clipped = clipToSrgb(current);
		const e = deltaEOk(oklchToOklab(current), labOf(clipped));
		if (e < JND) {
			if (JND - e < GAMUT_EPSILON) return clipped;
			minInGamut = false;
			min = chroma;
		} else {
			max = chroma;
		}
	}
	return clipped;
}

export function rgbToOklch(rgb: Rgb): Oklch {
	const [L, a, b] = linearRgbToOklab(linearise(rgb.r), linearise(rgb.g), linearise(rgb.b));
	return oklabToOklch(L, a, b);
}

// ---------------------------------------------------------------------------
// Hex and HSL. HSL exists here for exactly one reason: the brand hue ban.
// ---------------------------------------------------------------------------

export function toHex(rgb: Rgb): string {
	const ch = (v: number) =>
		Math.round(Math.min(1, Math.max(0, v)) * 255)
			.toString(16)
			.padStart(2, "0");
	return `#${ch(rgb.r)}${ch(rgb.g)}${ch(rgb.b)}`;
}

export function fromHex(hex: string): Rgb {
	const h = hex.replace("#", "").trim();
	const full = h.length === 3 ? h.split("").map((c) => c + c).join("") : h;
	if (!/^[0-9a-fA-F]{6}$/.test(full)) throw new Error(`not a hex colour: ${hex}`);
	return {
		r: Number.parseInt(full.slice(0, 2), 16) / 255,
		g: Number.parseInt(full.slice(2, 4), 16) / 255,
		b: Number.parseInt(full.slice(4, 6), 16) / 255,
	};
}

/**
 * Perceptual chroma below which a colour has no hue worth banning.
 *
 * This threshold is load-bearing, so here is the reasoning rather than a magic
 * number. HSL saturation is the wrong test: #fffbfd is a near-white with an
 * HSL saturation of 100 percent, because at lightness 0.99 the denominator
 * (2 - max - min) collapses. Judged on HSL, every warm near-white tint reads as
 * a fully saturated hue and the hue ANGLE is 8-bit rounding noise - a tint
 * authored at hue 355 comes back reading 339, which is inside the banned band.
 * That is a false refusal on a colour BRAND.md itself ships (its light-mode
 * bg-0 is #FFFDF9, exactly this kind of tint).
 *
 * Oklab chroma is the right test because it is perceptual. 0.02 sits an order
 * of magnitude below a real accent (a vivid orange is around 0.16) and above
 * every neutral this package generates (0.008, borders 0.012). A colour under
 * 0.02 chroma cannot read as violet to anyone; there is no room in it to hide
 * one. The ban is not weakened, it is applied where hue actually exists.
 */
const ACHROMATIC_CHROMA = 0.02;

export function renderedHue(rgb: Rgb): number | null {
	if (rgbToOklch(rgb).c < ACHROMATIC_CHROMA) return null;
	const max = Math.max(rgb.r, rgb.g, rgb.b);
	const min = Math.min(rgb.r, rgb.g, rgb.b);
	const delta = max - min;
	if (delta === 0) return null;
	let hue: number;
	if (max === rgb.r) hue = ((rgb.g - rgb.b) / delta) % 6;
	else if (max === rgb.g) hue = (rgb.b - rgb.r) / delta + 2;
	else hue = (rgb.r - rgb.g) / delta + 4;
	hue *= 60;
	if (hue < 0) hue += 360;
	return hue;
}

// ---------------------------------------------------------------------------
// WCAG 2.2 contrast. The gate.
// ---------------------------------------------------------------------------

/**
 * WCAG 2.2 relative luminance. Coefficients 0.2126 / 0.7152 / 0.0722 and the
 * 0.04045 threshold, both verbatim from the WCAG 2.2 glossary. The spec carries
 * an explicit note that the pre-May-2021 value 0.03928 is superseded; some
 * libraries still ship the old one.
 */
export function relativeLuminance(rgb: Rgb): number {
	return 0.2126 * linearise(rgb.r) + 0.7152 * linearise(rgb.g) + 0.0722 * linearise(rgb.b);
}

/** (L1 + 0.05) / (L2 + 0.05), symmetric, range 1 to 21. WCAG 2.2. */
export function contrastRatio(a: Rgb, b: Rgb): number {
	const la = relativeLuminance(a);
	const lb = relativeLuminance(b);
	return la > lb ? (la + 0.05) / (lb + 0.05) : (lb + 0.05) / (la + 0.05);
}

/** WCAG 2.2 AA floors. 1.4.3 body 4.5, large text 3.0; 1.4.11 non-text 3.0. */
export const CONTRAST_FLOOR = {
	body: 4.5,
	large: 3.0,
	nonText: 3.0,
} as const;

/**
 * Advisory perceptual separation: absolute Oklab lightness difference, 0-1.
 * NOT a contrast standard and never presented as one. It exists because the
 * WCAG ratio is famously poor at discriminating dark-on-dark pairs, and a
 * ranking function needs a signal there. Unencumbered by any licence.
 */
export function lightnessSeparation(a: Rgb, b: Rgb): number {
	return Math.abs(rgbToOklch(a).l - rgbToOklch(b).l);
}
