/**
 * 8gent Toolshed - GitHub Advanced Tools
 *
 * OpenViktor-inspired deep GitHub integration for issue management,
 * PR workflows, gists/artifacts, and repository analysis.
 * Uses `gh` CLI for all GitHub API interactions.
 */

import { execSync } from "child_process";

// ── Helpers ─────────────────────────────────────────

function run(cmd: string, cwd?: string): string {
  try {
    return execSync(cmd, {
      cwd: cwd || process.cwd(),
      encoding: "utf-8",
      timeout: 30000,
    }).trim();
  } catch (err: any) {
    throw new Error(err.stderr?.trim() || err.message);
  }
}

function ghApi(endpoint: string, method = "GET", body?: object): any {
  let cmd = `gh api ${endpoint} --method ${method}`;
  if (body) {
    cmd += ` --input -`;
    return JSON.parse(
      execSync(cmd, {
        input: JSON.stringify(body),
        encoding: "utf-8",
        timeout: 30000,
      }).trim()
    );
  }
  return JSON.parse(run(cmd));
}

// ── Types ───────────────────────────────────────────

export interface RepoStats {
  commitsThisWeek: number;
  openPRs: number;
  openIssues: number;
  contributors: string[];
  defaultBranch: string;
  repoName: string;
}

// ── Issue Management ────────────────────────────────

/**
 * Auto-create a GitHub issue for a persistent benchmark failure.
 * Labels with "benchmark-failure" and "automated" for tracking.
 */
export async function createIssueFromFailure(
  benchmark: string,
  error: string,
  score: number
): Promise<string> {
  const title = `Benchmark failure: ${benchmark} (score: ${score.toFixed(2)})`;
  const body = [
    `## Benchmark Failure Report`,
    ``,
    `| Field | Value |`,
    `|-------|-------|`,
    `| **Benchmark** | \`${benchmark}\` |`,
    `| **Score** | ${score.toFixed(4)} |`,
    `| **Date** | ${new Date().toISOString()} |`,
    ``,
    `### Error`,
    `\`\`\``,
    error,
    `\`\`\``,
    ``,
    `---`,
    `*Auto-generated by 8gent benchmark runner*`,
  ].join("\n");

  const escapedTitle = title.replace(/"/g, '\\"');
  const result = run(
    `gh issue create --title "${escapedTitle}" --body "${body.replace(/"/g, '\\"')}" --label "benchmark-failure,automated"`
  );
  return result; // Returns the issue URL
}

/**
 * Update a pinned issue with the latest benchmark scores.
 * Finds or creates a "Benchmark Dashboard" issue.
 */
export async function syncBenchmarkResults(
  scores: Record<string, number>
): Promise<void> {
  const dashboardTitle = "Benchmark Dashboard";

  // Find existing dashboard issue
  const existing = run(
    `gh issue list --search "${dashboardTitle} in:title" --state open --json number,title --limit 1`
  );
  const issues = JSON.parse(existing || "[]");

  const rows = Object.entries(scores)
    .map(([name, score]) => {
      const emoji = score >= 0.8 ? "🟢" : score >= 0.5 ? "🟡" : "🔴";
      return `| ${emoji} ${name} | ${score.toFixed(4)} |`;
    })
    .join("\n");

  const body = [
    `## 8gent Benchmark Scores`,
    ``,
    `*Last updated: ${new Date().toISOString()}*`,
    ``,
    `| Benchmark | Score |`,
    `|-----------|-------|`,
    rows,
    ``,
    `---`,
    `*Auto-updated by 8gent benchmark sync*`,
  ].join("\n");

  if (issues.length > 0) {
    run(
      `gh issue edit ${issues[0].number} --body "${body.replace(/"/g, '\\"')}"`
    );
  } else {
    run(
      `gh issue create --title "${dashboardTitle}" --body "${body.replace(/"/g, '\\"')}" --label "dashboard,automated" --pin`
    );
  }
}

/**
 * Create a GitHub Projects (v2) board.
 */
export async function createProjectBoard(
  name: string,
  columns: string[]
): Promise<string> {
  // Get the repo owner
  const repoInfo = run(`gh repo view --json owner,name`);
  const { owner, name: repoName } = JSON.parse(repoInfo);

  // Create project
  const result = run(
    `gh project create --owner "${owner.login}" --title "${name.replace(/"/g, '\\"')}"`
  );

  // Extract project number from the URL
  const projectNumber = result.match(/\/(\d+)\s*$/)?.[1];
  if (!projectNumber) return result;

  // Add status field columns
  for (const col of columns) {
    try {
      run(
        `gh project field-create ${projectNumber} --owner "${owner.login}" --name "${col}" --data-type TEXT`
      );
    } catch {
      // Column creation might not be supported via CLI; skip silently
    }
  }

  return result;
}

/**
 * Add an issue to a GitHub Project board.
 */
export async function addToProject(
  issueUrl: string,
  projectId: string,
  _column: string
): Promise<void> {
  run(`gh project item-add ${projectId} --url "${issueUrl}"`);
}

// ── PR Workflow ─────────────────────────────────────

/**
 * Create a PR with benchmark results formatted in the body.
 */
export async function createBenchmarkPR(
  branch: string,
  scores: Record<string, number>,
  improvements: string[]
): Promise<string> {
  const scoreRows = Object.entries(scores)
    .map(([name, score]) => `| ${name} | ${score.toFixed(4)} |`)
    .join("\n");

  const improvementList = improvements.map((i) => `- ${i}`).join("\n");

  const body = [
    `## Benchmark Results`,
    ``,
    `| Benchmark | Score |`,
    `|-----------|-------|`,
    scoreRows,
    ``,
    `### Improvements`,
    improvementList || "_No specific improvements noted._",
    ``,
    `---`,
    `*Generated by 8gent benchmark PR workflow*`,
  ].join("\n");

  const title = `bench: update scores (${Object.keys(scores).length} benchmarks)`;
  const result = run(
    `gh pr create --head "${branch}" --title "${title}" --body "${body.replace(/"/g, '\\"')}"`
  );
  return result;
}

/**
 * Add a comment to a pull request.
 */
export async function addPRComment(
  prNumber: number,
  comment: string
): Promise<void> {
  run(
    `gh pr comment ${prNumber} --body "${comment.replace(/"/g, '\\"')}"`
  );
}

/**
 * Request review from specific GitHub users on a PR.
 */
export async function requestReview(
  prNumber: number,
  reviewers: string[]
): Promise<void> {
  const reviewerList = reviewers.join(",");
  run(`gh pr edit ${prNumber} --add-reviewer "${reviewerList}"`);
}

// ── Gists & Artifacts ───────────────────────────────

/**
 * Create a public gist with competition/benchmark results.
 */
export async function createResultsGist(
  title: string,
  content: string
): Promise<string> {
  const filename = title.replace(/[^a-zA-Z0-9-_]/g, "-") + ".md";
  // Write content to a temp file, create gist, clean up
  const tmpFile = `/tmp/8gent-gist-${Date.now()}.md`;
  execSync(`cat > "${tmpFile}"`, {
    input: `# ${title}\n\n${content}\n`,
    encoding: "utf-8",
  });

  const result = run(
    `gh gist create "${tmpFile}" --desc "${title.replace(/"/g, '\\"')}" --public`
  );

  execSync(`rm -f "${tmpFile}"`);
  return result; // Returns the gist URL
}

/**
 * Update an existing gist's content.
 */
export async function updateGist(
  gistId: string,
  content: string
): Promise<void> {
  const tmpFile = `/tmp/8gent-gist-update-${Date.now()}.md`;
  execSync(`cat > "${tmpFile}"`, { input: content, encoding: "utf-8" });

  run(`gh gist edit ${gistId} "${tmpFile}"`);
  execSync(`rm -f "${tmpFile}"`);
}

// ── Repository Analysis ─────────────────────────────

/**
 * Get repository stats: commits this week, open PRs/issues, contributors.
 */
export async function getRepoStats(): Promise<RepoStats> {
  const repoJson = run(
    `gh repo view --json name,defaultBranchRef`
  );
  const repo = JSON.parse(repoJson);

  const oneWeekAgo = new Date(Date.now() - 7 * 24 * 60 * 60 * 1000)
    .toISOString()
    .split("T")[0];

  const commitsThisWeek = parseInt(
    run(`git log --oneline --since="${oneWeekAgo}" | wc -l`).trim(),
    10
  );

  const openPRs = parseInt(
    run(`gh pr list --state open --json number | jq length`),
    10
  );

  const openIssues = parseInt(
    run(`gh issue list --state open --json number | jq length`),
    10
  );

  const contributorsRaw = run(
    `git log --since="${oneWeekAgo}" --format='%an' | sort -u`
  );
  const contributors = contributorsRaw
    .split("\n")
    .filter(Boolean);

  return {
    commitsThisWeek,
    openPRs,
    openIssues,
    contributors,
    defaultBranch: repo.defaultBranchRef?.name || "main",
    repoName: repo.name,
  };
}

/**
 * Get branch protection rules for a given branch.
 */
export async function getBranchProtection(branch: string): Promise<any> {
  const repoJson = run(`gh repo view --json nameWithOwner`);
  const { nameWithOwner } = JSON.parse(repoJson);

  try {
    const result = run(
      `gh api repos/${nameWithOwner}/branches/${branch}/protection`
    );
    return JSON.parse(result);
  } catch (err: any) {
    if (err.message.includes("404") || err.message.includes("Not Found")) {
      return { protected: false, message: "No branch protection rules configured" };
    }
    throw err;
  }
}
