/**
 * 8gent Toolshed - GitHub Cron Job Integration
 *
 * OpenViktor-inspired cron scheduling for GitHub Actions workflows.
 * Creates and manages scheduled workflows for benchmarks, dependency
 * updates, stale issues, and custom automation.
 */

import { execSync } from "child_process";
import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from "fs";
import { join } from "path";

function run(cmd: string, cwd?: string): string {
  try {
    return execSync(cmd, {
      cwd: cwd || process.cwd(),
      encoding: "utf-8",
      timeout: 30000,
    }).trim();
  } catch (err: any) {
    throw new Error(err.stderr?.trim() || err.message);
  }
}

// ── Types ───────────────────────────────────────────

interface ScheduledAction {
  name: string;
  schedule: string;
  lastRun?: string;
  path: string;
}

// ── Core Functions ──────────────────────────────────

/**
 * Create a GitHub Actions workflow with a cron trigger.
 * Writes a `.github/workflows/{name}.yml` file.
 *
 * @param name — Workflow name (used as filename, kebab-cased)
 * @param schedule — Cron expression (e.g., "0 2 * * *" for 2AM daily)
 * @param script — The shell script/command to run in the workflow
 */
export async function scheduleGitHubAction(
  name: string,
  schedule: string,
  script: string
): Promise<void> {
  const repoRoot = run("git rev-parse --show-toplevel");
  const workflowDir = join(repoRoot, ".github", "workflows");

  if (!existsSync(workflowDir)) {
    mkdirSync(workflowDir, { recursive: true });
  }

  const filename = name.replace(/[^a-zA-Z0-9-]/g, "-").toLowerCase();
  const workflowPath = join(workflowDir, `${filename}.yml`);

  const workflow = `# Auto-generated by 8gent GitHub Cron Integration
# Schedule: ${schedule}
name: ${name}

on:
  schedule:
    - cron: '${schedule}'
  workflow_dispatch: {}

permissions:
  contents: read
  issues: write

jobs:
  ${filename}:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run scheduled task
        run: |
${script
  .split("\n")
  .map((line) => `          ${line}`)
  .join("\n")}
        env:
          GITHUB_TOKEN: \${{ secrets.GITHUB_TOKEN }}
          OPENROUTER_API_KEY: \${{ secrets.OPENROUTER_API_KEY }}
`;

  writeFileSync(workflowPath, workflow, "utf-8");
}

/**
 * List all scheduled GitHub Actions workflows in the repo.
 * Parses .github/workflows/*.yml for cron schedules and checks last run via gh CLI.
 */
export async function listScheduledActions(): Promise<ScheduledAction[]> {
  const repoRoot = run("git rev-parse --show-toplevel");
  const workflowDir = join(repoRoot, ".github", "workflows");

  if (!existsSync(workflowDir)) {
    return [];
  }

  const files = readdirSync(workflowDir).filter(
    (f) => f.endsWith(".yml") || f.endsWith(".yaml")
  );

  const actions: ScheduledAction[] = [];

  for (const file of files) {
    const filePath = join(workflowDir, file);
    const content = readFileSync(filePath, "utf-8");

    // Extract cron schedule
    const cronMatch = content.match(/cron:\s*['"](.+?)['"]/);
    if (!cronMatch) continue;

    // Extract name
    const nameMatch = content.match(/^name:\s*(.+)$/m);
    const name = nameMatch?.[1]?.trim() || file.replace(/\.ya?ml$/, "");

    // Try to get last run time from GitHub
    let lastRun: string | undefined;
    try {
      const runsJson = run(
        `gh run list --workflow="${file}" --limit 1 --json startedAt`
      );
      const runs = JSON.parse(runsJson || "[]");
      if (runs.length > 0) {
        lastRun = runs[0].startedAt;
      }
    } catch {
      // Workflow might not have any runs yet
    }

    actions.push({
      name,
      schedule: cronMatch[1],
      lastRun,
      path: filePath,
    });
  }

  return actions;
}

// ── Cron Templates ──────────────────────────────────

/**
 * Create a nightly benchmark cron workflow.
 * Runs benchmarks at 2AM UTC and creates issues on failure.
 */
export async function benchmarkCron(): Promise<void> {
  await scheduleGitHubAction(
    "nightly-benchmarks",
    "0 2 * * *",
    `bun run benchmarks/autoresearch/harness.ts 2>&1 | tee benchmark-output.log
EXIT_CODE=\${PIPESTATUS[0]}
if [ $EXIT_CODE -ne 0 ]; then
  gh issue create \\
    --title "Nightly benchmark failure $(date +%Y-%m-%d)" \\
    --body "$(cat benchmark-output.log | tail -100)" \\
    --label "benchmark-failure,automated"
fi`
  );
}

/**
 * Create a weekly dependency update check workflow.
 * Runs every Monday at 9AM UTC.
 */
export async function dependencyUpdateCron(): Promise<void> {
  await scheduleGitHubAction(
    "weekly-dependency-check",
    "0 9 * * 1",
    `echo "## Dependency Update Report" > dep-report.md
echo "" >> dep-report.md
echo "### Outdated packages" >> dep-report.md
bun outdated 2>&1 >> dep-report.md || true
echo "" >> dep-report.md
echo "### Security audit" >> dep-report.md
bun audit 2>&1 >> dep-report.md || true
echo "" >> dep-report.md
echo "*Generated on $(date)*" >> dep-report.md

gh issue create \\
  --title "Weekly dependency report $(date +%Y-%m-%d)" \\
  --body "$(cat dep-report.md)" \\
  --label "dependencies,automated"`
  );
}

/**
 * Create a monthly stale issue cleanup workflow.
 * Runs on the 1st of each month at 6AM UTC.
 */
export async function staleIssueCron(): Promise<void> {
  await scheduleGitHubAction(
    "monthly-stale-issues",
    "0 6 1 * *",
    `# Close issues with no activity for 90+ days
STALE_ISSUES=$(gh issue list --state open --json number,updatedAt --jq '.[] | select((.updatedAt | fromdateiso8601) < (now - 7776000)) | .number')

for issue in $STALE_ISSUES; do
  gh issue comment $issue --body "This issue has been automatically closed due to 90 days of inactivity. If this is still relevant, please reopen it."
  gh issue close $issue --reason "not planned"
done

CLOSED_COUNT=$(echo "$STALE_ISSUES" | wc -w)
echo "Closed $CLOSED_COUNT stale issues"`
  );
}
